Repository woorifisa-projects-3rd/WeKids-FE, pull requests merged in 2024-12, with the labels that each got.

#109 [FEAT] 미션 등록 화면
  auth.js
  package-lock.json
  src/app/(auth)/signup/regform/RegForm.jsx
  src/app/(auth)/signup/select/page.jsx
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/(transaction)/transaction-history/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/done/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/app/child/card/card-select/page.jsx
  src/app/child/card/page.jsx
  src/app/mission-add/page.jsx
  src/app/page.js
  src/app/parent/account/page.jsx
  src/app/parent/card/apply/confirm/page.jsx
  src/app/parent/card/delivery/completed/page.jsx
  src/app/parent/card/delivery/page.jsx
  src/app/parent/card/verification/page.jsx
  src/app/t분리전/zrchieve/page.jsx
  src/middleware.js
  src/services/parents.js
  src/services/transaction.js
  src/stores/accountStore.js
  src/stores/cardStore.js
  src/stores/transactionStore.js
  src/ui/components/account/AccountList.jsx
  src/ui/components/atoms/InputDateBox.jsx
  src/ui/components/atoms/InputTextBox.jsx
  src/ui/components/atoms/MissionModal.jsx
  src/ui/components/auth/SignIn.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/card/CardAddress.jsx
  src/ui/components/card/CardDisplay.jsx
  src/ui/components/card/CardRequestReview.jsx
  src/ui/components/card/InnerText.jsx
  src/ui/components/mission/MissionConfirmModal.jsx
  src/ui/components/mission/MissionDetail.jsx
  src/ui/components/mission/parent/ButtonGroup.jsx
  src/ui/components/mission/parent/MissionAddComponent.jsx
  src/ui/components/signup/AccountItem.jsx
  src/ui/components/signup/Bottom.jsx
  src/ui/components/signup/ChildInputForm.jsx
  src/ui/components/signup/Digit4PasswordButton.jsx
  src/ui/components/signup/IdentificationBox.jsx
  src/ui/components/signup/IdentificationForm.jsx
  src/ui/components/signup/ParentInfoTop.jsx
  src/ui/components/signup/PasswordBottom.jsx
  src/ui/components/signup/SignUpFooter.jsx
  src/ui/components/signup/SignUpHeader.jsx
  src/ui/components/transaction/transaction-history/AccountHistoryHeader.jsx
  src/ui/components/transaction/transaction-history/TopBar.jsx
  src/ui/components/transaction/transaction-history/TransactionsView.jsx
  src/ui/components/transfer/TransferModal.jsx
  tailwind.config.js
Labels: ✨ feature

#124 [Feat] 홈 관련 바뀐 디자인 적용 및 link 적용
  prettierrc.json
  public/images/noCardIconImg.svg
  public/images/tinypingGroupImg.svg
  public/images/weebeGropImg.svg
  src/app/(auth)/signup/regform/RegForm.jsx
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/globals.css
  src/app/page.js
  src/services/parents.js
  src/services/transaction.js
  src/ui/components/card/CardAddress.jsx
  src/ui/components/home/AccountCardLayout.jsx
  src/ui/components/home/MainHome.jsx
  src/ui/components/home/MessageBox.jsx
  src/ui/components/home/child/ChildView.jsx
  src/ui/components/home/child/EmptyAccountCard.jsx
  src/ui/components/home/mission/ChildMissionCard.jsx
  src/ui/components/home/mission/MissionCardLayout.jsx
  src/ui/components/home/mission/ParentMissionCard.jsx
  src/ui/components/home/parent/AccountGuide.jsx
  src/ui/components/home/parent/ChildNoCard.jsx
  src/ui/components/home/parent/EmptyAccountCard.jsx
  src/ui/components/home/parent/HasAccount.jsx
  src/ui/components/home/parent/NoAccountCard.jsx
  src/ui/components/home/parent/NoAccountView.jsx
  src/ui/components/home/parent/ParentHome.jsx
  src/ui/components/mission/NoMissionCardLayout copy.jsx
  src/ui/components/mission/NoMissionMessageBox.jsx
  src/ui/components/mission/child/ChildNoMissionCard.jsx
  src/ui/components/mission/parent/ButtonGroup.jsx
  src/ui/components/mission/parent/ParentNoMissionCard.jsx
  src/ui/components/signup/IdentificationBox.jsx
  src/util/db/index.js
  src/util/stringHighlight.js
  tailwind.config.js
Labels: ✨ feature, ♻️ refactor

#116 [FEAT] 부모 미션 승인 뷰
  src/app/(transfer)/account-list/page.jsx
  src/app/mission-accept/page.jsx
  src/constants/mission.js
  src/stores/userStore.js
  src/ui/components/mission/MissionModal.jsx
  src/ui/components/mission/parent/MissionAcceptComponent.jsx
  tailwind.config.js
Labels: ✨ feature

#112 [FEAT] 미션 인증 뷰(사진 업로드 기능 포함)
  package-lock.json
  package.json
  public/images/backupImg.svg
  src/app/mission-request/page.jsx
  src/ui/components/mission/MissionDetail.jsx
  src/ui/components/mission/child/MissionRequestComponent.jsx
Labels: ✨ feature

#117 [FEAT] 미션 콘텐츠 화면, 필터링 기능
  public/images/cross.svg
  src/app/globals.css
  src/app/mission/child/list/page.jsx
  src/app/mission/parent/list/page.jsx
  src/stores/missionFilterStore
  src/ui/components/mission/list/ChildMissionContent.jsx
  src/ui/components/mission/list/FilterHeader.jsx
  src/ui/components/mission/list/MissionCard.jsx
  src/ui/components/mission/list/MissionContent.jsx
  src/ui/components/mission/list/MissionFilterModal.jsx
  src/ui/components/mission/list/MissionFooter.jsx
  src/ui/components/mission/list/MissionList.jsx
  src/ui/components/mission/list/ProfileSection.jsx
  src/ui/components/mission/list/StateBadge.jsx
  src/ui/components/mission/list/StateIcon.jsx
  src/ui/components/mission/list/StateIconBadge.jsx
  src/util/missionUtils.js
  tailwind.config.js
Labels: ✨ feature

#111 [FEAT] [송금] [송금 비밀번호 등록] [송금 완료 페이지] 구현
  package-lock.json
  package.json
  src/app/(transfer)/transfer/done/page.jsx
  src/app/mission/transfer/done/page.jsx
  src/app/mission/transfer/page.jsx
  src/app/mission/transfer/password/page.jsx
  src/constants/common.js
  src/ui/components/atoms/Sharebutton.jsx
  src/ui/components/signup/PasswordBottom.jsx
  src/ui/components/signup/PasswordTop.jsx
  src/ui/components/transfer/TransferComplete.jsx
Labels: ✨ feature

#132 [REFACT] 카드 디자인 커스텀 뷰 API
  auth.js
  src/apis/design.js
  src/apis/transaction.js
  src/app/child/card/card-select/page.jsx
  src/app/child/card/complete/page.jsx
  src/stores/cardStore.js
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/card-select/CharacterButton.jsx
  src/ui/components/card/ChoiceDesign.jsx
  src/ui/components/transaction/transaction-history/TransactionsView.jsx
Labels: 🐞bug

#141 [FIX] 디자인 커스텀 뷰 QA
  src/apis/design.js
  src/app/child/card/card-select/page.jsx
  src/app/child/card/complete/page.jsx
  src/stores/cardStore.js
  src/ui/components/card/ChoiceDesign.jsx
Labels: 🐞bug

#146 [REFACT] 디자인 생성 API 수정
  src/apis/design.js
  src/app/child/card/card-select/page.jsx
  src/app/child/card/complete/page.jsx
  src/ui/components/card/ChoiceDesign.jsx
Labels: ♻️ refactor

#149 [FEAT] 미션
  next.config.mjs
  src/apis/parents.js
  src/apis/transaction.js
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/mission/transfer/page.jsx
  src/constants/assign.js
  src/query/accountQuery.js
  src/query/parentQuery.js
  src/ui/components/account/AccountList.jsx
  src/ui/components/alarm/AlarmCard.jsx
  src/ui/components/alarm/AlarmComponent.jsx
  src/ui/components/mission/MissionDetail.jsx
  src/ui/components/mission/child/ChildMissionHome.jsx
  src/ui/components/mission/child/ChildMissionList.jsx
  src/ui/components/mission/child/MissionRequestComponent.jsx
  src/ui/components/mission/parent/MissionAcceptComponent.jsx
  src/ui/components/mission/parent/ParentMissionHome.jsx
  src/ui/components/mission/parent/ParentMissionList.jsx
  src/ui/components/mission/parent/TransferCheck.jsx
  src/ui/components/signup/PasswordTop.jsx
  src/ui/components/transfer/TransferComplete.jsx
Labels: ✨ feature
