Repository woorifisa-projects-3rd/WeKids-FE, pull requests merged in 2024-11, with the labels that each got.

#4 [FEAT] 모달, 키패드, 거래 내역 박스 컴포넌트 구현
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/WooridaumB.ttf
  public/fonts/WooridaumL.ttf
  public/fonts/WooridaumR.ttf
  tailwind.config.js
  ui/components/KeyPad.js
  ui/components/Modal.js
  ui/components/TransactionBox.js
Labels: ✨ feature

#5 [FEAT] 이체 버튼, 다음 버튼, 공유 버튼(이미지o), 파란 버튼(이미지x), 흰 사각형, 프로필 구현
  public/images/profile.jpg
  tailwind.config.js
  ui/components/Modal/BlueButton.js
  ui/components/Modal/NextButton.js
  ui/components/Modal/Rectangle.js
  ui/components/Modal/Sharebutton.js
  ui/components/Modal/Transferbutton.js
Labels: ✨ feature

#6 Feat/#1 프로젝트 초기 세팅
  app/favicon.ico
  app/fonts/GeistMonoVF.woff
  app/fonts/GeistVF.woff
  app/globals.css
  app/layout.js
  app/page.js
  public/globe.svg
  public/icons/file.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/[home]/transactions/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/hooks/empty.js
  src/services/auth.js
  src/ui/Components/Upload.js
  src/util/db/index.js
  src/util/empty.js
Labels: ✨ feature

#13 [FIX] 공통 컴포넌트 CSS 수정
  public/images/Avatar.svg
  src/ui/Components/atoms/Modal/BlueButton.js
  src/ui/Components/atoms/Modal/NextButton.js
  src/ui/Components/atoms/Modal/Profile.js
  src/ui/Components/atoms/Modal/Rectangle.js
  src/ui/Components/atoms/Modal/Sharebutton.js
  src/ui/Components/atoms/Modal/Transferbutton.js
  src/ui/Components/atoms/Upload.js
  tailwind.config.js
Labels: ♻️ refactor

#16 [REFACTOR] 모달 컴포넌트 기능 추가 및 키패드 일부 코드 변경
  src/ui/Components/atoms/KeyPad.js
  src/ui/Components/atoms/Modal.js
Labels: ♻️ refactor

#17 [FEAT] 이체 완료 뷰 구현
  src/app/account-list/account/done/page.js
  src/app/account-list/account/done/page.jsx
  src/app/globals.css
  src/ui/Components/atoms/Modal/Sharebutton.js
Labels: ✨ feature

#19 [FEAT] 이체 목록 조회 뷰 구현
  src/app/account-list/page.jsx
  src/app/globals.css
  src/stores/useTransactionStore.js
  src/ui/Components/atoms/TransferItem.js
Labels: ✨ feature

#20 [FEAT] 계좌내역 조회 뷰
  package-lock.json
  package.json
  public/icons/backarrow.svg
  public/icons/setting.svg
  src/app/transaction-history/page.jsx
  src/services/transactions/transactionApi.jsx
  src/stores/useTransFilterStore.jsx
  src/ui/Components/transactions/transavtions-history/TopBar.jsx
  src/ui/Components/transactions/transavtions-history/TransFilterModal.jsx
  src/ui/Components/transactions/transavtions-history/TransactionFilter.jsx
  src/ui/Components/transactions/transavtions-history/TransactionItem.jsx
  src/ui/Components/transactions/transavtions-history/TransactionsView.jsx
  src/ui/Components/transactions/transavtions-history/empty.js
Labels: ✨ feature

#21 [FEAT] 송금 화면 뷰 구현
  src/app/account-list/account/page.jsx
  src/app/globals.css
  src/stores/useTransactionStore.js
  src/ui/Components/transactions/transfer/TransferAmoutDisplay.jsx
  src/ui/Components/transactions/transfer/TransferModal.jsx
  src/ui/Components/transactions/transfer/TransferOptions.jsx
Labels: ✨ feature

#26 Refact/#24 jabin
  public/icons/alarmIcon.svg
  public/icons/backarrowIcon.svg
  public/icons/copyIcon.svg
  public/icons/personIcon.svg
  public/icons/settingIcon.svg
  public/icons/uploadIcon.svg
  public/images/accountWeebeeImg.svg
  public/images/avatarImg.svg
  public/images/bombomImg.svg
  public/images/dalboImg.svg
  public/images/logoImg.svg
  public/images/profile.jpg
  src/app/(transfer)/transfer/page.jsx
  src/constants/common.js
  src/constants/transaction.js
  src/ui/Components/atoms/NextButton.jsx
  src/ui/Components/atoms/Profile.jsx
  src/ui/Components/atoms/Sharebutton.jsx
  src/ui/Components/home/BlueCardBox.jsx
  src/ui/Components/transactions/detail/ConfirmButton.jsx
  src/ui/Components/transactions/transavtions-history/TopBar.jsx
  src/ui/layout/Header.jsx
  src/util/characterInfo.js
Labels: ♻️ refactor

#25 Refact/#24 yeeun
  src/app/(home)/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/stores/accountSotre.js
  src/stores/accountStore.js
  src/stores/transactionStore.js
  src/stores/useTransFilterStore.js
  src/stores/useTransactionStore.js
  src/ui/Components/home/BlueCardBox.jsx
  src/ui/Components/transactions/detail/Memo.jsx
  src/ui/Components/transactions/transavtions-history/TransFilterModal.jsx
  src/ui/Components/transactions/transavtions-history/TransactionFilter.jsx
  src/ui/Components/transactions/transavtions-history/TransactionsView.jsx
Labels: ♻️ refactor

#34 [REFACTOR] 일부 뷰 font, color 수정
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/ui/Components/atoms/TransferItem.jsx
  src/ui/Components/home/BlueCardBox.jsx
  src/ui/Components/transaction/transaction-history/TopBar.jsx
  src/ui/Components/transaction/transaction-history/TransFilterModal.jsx
  src/ui/Components/transaction/transaction-history/TransactionFilter.jsx
  src/ui/Components/transaction/transaction-history/TransactionItem.jsx
  src/ui/Components/transaction/transaction-history/TransactionsView.jsx
  src/ui/Components/transfer/TransferAmoutDisplay.jsx
  src/ui/Components/transfer/TransferModal.jsx
  src/ui/Components/transfer/TransferOptions.jsx
Labels: ♻️ refactor

#33 [REFACTOR] font, color 수정
  src/app/(transfer)/transfer/done/page.jsx
  tailwind.config.js
Labels: ♻️ refactor

#42 [FEAT] 컬러수정, 폰트 추가, 컴포넌트화
  src/app/ui/button/page.jsx
  src/app/ui/input/page.jsx
  src/app/ui/popup/page.jsx
  src/ui/Components/atoms/CustomButton.jsx
  src/ui/Components/atoms/InputTextBox.jsx
  src/ui/Components/molecules/PopupMessage.jsx
  tailwind.config.js
Labels: ✨ feature

#43 [FEAT] 부모 선택 뷰
  src/app/(signup)/select/page.jsx
  src/ui/Components/signup/ParentChildSelector.jsx
  src/ui/Components/signup/SelectorItem.jsx
Labels: ✨ feature

#40 [FEAT] 회원가입뷰 구현
  package-lock.json
  package.json
  src/app/(signup)/select/self/page.jsx
  src/constants/assign.js
  src/ui/Components/atoms/signup/Assign.jsx
  src/ui/Components/atoms/signup/Bottom.jsx
  src/ui/Components/atoms/signup/Top.jsx
Labels: ✨ feature

#47 [REFACT] 바뀐 홈 화면 디자인 수정 및 공통 색상 변경
  package-lock.json
  public/images/accountWeebeeImg.svg
  public/images/avatarImg.svg
  public/images/bombomImg.svg
  public/images/chachapingImg.svg
  public/images/dadapingImg.svg
  public/images/dalboImg.svg
  public/images/gogopingImg.svg
  public/images/hachupingImg.svg
  public/images/happingImg.svg
  public/images/lalapingImg.svg
  public/images/logoImg.svg
  src/app/(home)/page.jsx
  src/app/globals.css
  src/constants/common.js
  src/ui/Components/atoms/Profile.jsx
  src/ui/Components/home/BlueCardBox.jsx
  src/ui/layout/Header.jsx
  tailwind.config.js
Labels: ♻️ refactor

#49 [FEAT] 회원가입 완료 뷰 구현
  src/app/(signup)/select/self/confirm/page.jsx
  src/app/(signup)/select/self/page.jsx
  src/ui/Components/signup/Assign.jsx
  src/ui/Components/signup/Bottom.jsx
  src/ui/Components/signup/ConfirmItem.jsx
  src/ui/Components/signup/Top.jsx
Labels: ✨ feature

#46 [FEAT] SPRINT2 공통 컴포넌트(캐릭터 카드, 모달, 선택 박스)
  src/ui/Components/atoms/CharacterCard.jsx
  src/ui/Components/atoms/Modal.jsx
  src/ui/Components/transfer/TransferModal.jsx
Labels: ✨ feature

#48 [FEAT] 간편 비밀번호 입력
  src/app/(signup)/select/self/password/page.jsx
  src/constants/transaction.js
  src/ui/Components/atoms/KeyPad.jsx
  src/ui/Components/signup/PasswordBottom.jsx
  src/ui/Components/signup/PasswordTop.jsx
Labels: ✨ feature

#53 [FEAT] 부모 계좌 불러오는 뷰
  public/images/woorisvg.svg
  src/app/(signup)/account/page.jsx
  src/app/(signup)/select/page.jsx
  src/app/(transfer)/transfer/done/page.jsx
  src/app/account-list/account/done/page.jsx
  src/ui/components/atoms/signup/Assign.jsx
  src/ui/components/atoms/signup/Bottom.jsx
  src/ui/components/atoms/signup/Top.jsx
  src/ui/components/signup/AccountItem.jsx
  src/ui/components/signup/ParentChildSelector.jsx
  src/ui/components/signup/SelectorAccount.jsx
Labels: ✨ feature

#61 [FEAT] 카드 디자인 뷰
  .github/ISSUE_TEMPLATE/custom.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  postcss.config.js
  src/app/(signup)/select/page.jsx
  src/app/(signup)/select/phone/page.jsx
  src/app/(signup)/select/self/confirm/page.jsx
  src/app/(signup)/select/self/password/page.jsx
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/(transaction)/transaction-history/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/done/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/app/card/design/page.jsx
  src/app/globals.css
  src/constants/assign.js
  src/constants/common.js
  src/constants/transaction.js
  src/hooks/empty.js
  src/services/auth.js
  src/stores/accountStore.js
  src/ui/components/atoms/CharacterCard.jsx
  src/ui/components/atoms/KeyPad.jsx
  src/ui/components/atoms/Modal.jsx
  src/ui/components/atoms/Rectangle.jsx
  src/ui/components/atoms/Sharebutton.jsx
  src/ui/components/atoms/TransactionBox.jsx
  src/ui/components/card/ChoiceDesign.jsx
  src/ui/components/signup/Assign.jsx
  src/ui/components/signup/Bottom.jsx
  src/ui/components/signup/ConfirmItem.jsx
  src/ui/components/signup/ParentChildSelector.jsx
  src/ui/components/signup/PasswordBottom.jsx
  src/ui/components/signup/PasswordTop.jsx
  src/ui/components/signup/SelectorItem.jsx
  src/ui/components/signup/SignUpFooter.jsx
  src/ui/components/signup/SignUpHeader.jsx
  src/ui/components/signup/Top.jsx
  src/ui/components/transaction/transaction-history/TopBar.jsx
  src/ui/components/transaction/transaction-history/TransFilterModal.jsx
  src/ui/components/transaction/transaction-history/TransactionFilter.jsx
  src/ui/components/transaction/transaction-history/TransactionItem.jsx
  src/ui/components/transaction/transaction-history/TransactionsView.jsx
  src/ui/components/transfer/TransferAmoutDisplay.jsx
  src/ui/components/transfer/TransferModal.jsx
  src/ui/components/transfer/TransferOptions.jsx
Labels: ✨ feature

#62 [FEAT] 카드 발급 선택 뷰
  public/images/CardChip.svg
  src/app/(card-design)/card-select/page.jsx
  src/stores/cardStore.js
  src/ui/Components/card-select/CardCharacter.jsx
  src/ui/Components/card-select/CardIssueModal.jsx
  src/ui/Components/card-select/CharacterButton.jsx
  src/ui/Components/card-select/ColorButton.jsx
Labels: ✨ feature

#59 [FEAT] 카드 요청 발급 뷰(자식)
  src/app/card/page.jsx
  src/ui/components/card/CardRequestReview.jsx
  src/ui/components/card/InnerText.jsx
Labels: ✨ feature

#66 [FEAT] 계좌 생성 동의 자식 기본정보 입력 뷰
  src/app/(signup)/select/self/child/page.jsx
  src/app/(signup)/select/self/page.jsx
  src/app/globals.css
  src/ui/components/atoms/Loader.jsx
  src/ui/components/atoms/Modal.jsx
  src/ui/components/atoms/signup/Assign.jsx
  src/ui/components/atoms/signup/Bottom.jsx
  src/ui/components/atoms/signup/Top.jsx
  src/ui/components/signup/ChildInputForm.jsx
  src/ui/components/signup/LimitedInputBox.jsx
Labels: ✨ feature

#70 [FEAT] 알림 뷰
  public/images/notificationImg.svg
  src/app/(signup)/select/self/confirm/page.jsx
  src/app/(signup)/select/self/page.jsx
  src/app/(signup)/select/self/password/page.jsx
  src/app/alarm/page.jsx
  src/app/ui/input/page.jsx
  src/app/ui/popup/page.jsx
  src/constants/assign.js
  src/ui/components/atoms/AlarmCard.jsx
  src/ui/components/signup/Bottom.jsx
  src/ui/components/signup/ChildInputForm.jsx
  src/ui/components/signup/PasswordBottom.jsx
  src/ui/components/signup/SignUpFooter.jsx
  src/ui/components/signup/SignUpHeader.jsx
  src/ui/components/signup/Top.jsx
Labels: ✨ feature

#69 [FEAT] 카드 주소 입력 뷰
  src/app/card/delivery/page.jsx
  src/app/globals.css
  src/ui/Components/card-select/CardCharacter.jsx
  src/ui/components/atoms/Modal.jsx
  src/ui/components/card/CardAddress.jsx
  src/ui/components/card/CardAddressBottom.jsx
  src/ui/components/card/ChoiceDesign.jsx
  src/ui/components/signup/ParentChildSelector.jsx
Labels: ✨ feature

#85 [FEAT] 부모 동의 대기 뷰
  src/app/card/parent/page.jsx
Labels: ✨ feature

#84 [FEAT] 체크카드 신청하기 뷰
  public/images/busImg.svg
  public/images/familyImg.svg
  src/app/card/apply/page.jsx
Labels: ✨ feature

#87 [FEAT] 주민번호 입력 및 확인 뷰
  package-lock.json
  src/app/(signup)/select/self/identification/page.jsx
  src/app/card/parent/page.jsx
  src/ui/components/signup/IdentificationBox.jsx
  src/ui/components/signup/IdentificationForm.jsx
  src/ui/components/signup/LimitedInputBox.jsx
Labels: ✨ feature

#88 [Feat] 부모 자식에 따른 분기처리
  .gitmessage.txt
  src/app/(card-design)/card-select/page.jsx
  src/app/(home)/page.jsx
  src/app/(signup)/select/page.jsx
  src/app/(signup)/select/self/confirm/page.jsx
  src/app/account-list/account/done/page.jsx
  src/app/globals.css
  src/app/page.js
  src/app/user/page.jsx
  src/constants/common.js
  src/stores/userTypeStore.js
  src/ui/components/atoms/InputTextBox.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/home/BlueCardBox.jsx
  src/ui/components/home/MainHome.jsx
  src/ui/components/home/child/ChildView.jsx
  src/ui/components/home/parent/AccountGuide.jsx
  src/ui/components/home/parent/EmptyAccountCard.jsx
  src/ui/components/home/parent/HasAccount.jsx
  src/ui/components/home/parent/NoAccountView.jsx
  src/ui/components/home/parent/ParentStart.jsx
  src/ui/components/home/parent/ProfileSection.jsx
  src/ui/layout/Header.jsx
Labels: ✨ feature

#94 [FIX] 오류 수정
  package-lock.json
  src/app/(auth)/signup/regform/page.jsx
  src/app/(auth)/signup/regform/phone/page.jsx
  src/app/(auth)/signup/select/page.jsx
  src/app/(auth)/signup/select/parent/password/confirm/page.jsx
  src/app/(auth)/signup/select/parent/password/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/app/child/card/card-select/page.jsx
  src/app/parent/account/page.jsx
  src/app/parent/card/apply/password/page.jsx
  src/app/parent/card/delivery/page.jsx
  src/app/parent/card/verification/page.jsx
  src/app/t분리전/zrchieve/page.jsx
  src/constants/assign.js
  src/constants/common.js
  src/stores/accountStore.js
  src/ui/components/account/Account.jsx
  src/ui/components/account/Identification.jsx
  src/ui/components/atoms/AlarmCard.jsx
  src/ui/components/atoms/InputTextBox.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/card/CardRequestReview.jsx
  src/ui/components/card/InnerText.jsx
  src/ui/components/signup/IdentificationBox.jsx
  src/ui/components/signup/ParentInfoTop.jsx
  src/ui/components/signup/PasswordBottom.jsx
  src/ui/components/signup/PasswordTop.jsx
  src/ui/components/signup/SignUpFooter.jsx
  src/ui/components/signup/SignUpHeader.jsx
Labels: 🐞bug

#93 [FIX] 오류 수정
  src/constants/common.js
  src/ui/components/card-select/CardCharacter.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/molecules/PopupMessage.jsx
Labels: 🐞bug

#102 [FIX] 자녀/자식 일때 용돈주기 버튼 분기처리
  src/ui/components/card-select/CardCharacter.jsx
  src/ui/components/transaction/transaction-history/TopBar.jsx
Labels: ♻️ refactor

#101 [FEAT} account, transaction API 병합
  src/app/(transaction)/transaction-history/[trxId]/page.jsx
  src/app/(transaction)/transaction-history/page.jsx
  src/app/(transfer)/account-list/page.jsx
  src/app/(transfer)/transfer/done/page.jsx
  src/app/(transfer)/transfer/page.jsx
  src/app/layout.js
  src/app/parent/account/page.jsx
  src/app/parent/card/delivery/page.jsx
  src/app/parent/card/verification/page.jsx
  src/constants/transaction.js
  src/constants/url.js
  src/libs/session.js
  src/libs/temp.js
  src/services/account.js
  src/services/transaction.js
  src/stores/cardStore.js
  src/stores/transactionStore.js
  src/ui/components/QueryProvider.jsx
  src/ui/components/account/Account.jsx
  src/ui/components/account/Identification.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/molecules/PopupMessage.jsx
  src/ui/components/signup/AccountItem.jsx
  src/ui/components/signup/SignUpFooter.jsx
  src/ui/components/transaction/detail/Memo.jsx
  src/ui/components/transaction/transaction-history/TopBar.jsx
  src/ui/components/transaction/transaction-history/TransactionsView.jsx
  src/ui/components/transfer/TransferAmoutDisplay.jsx
  src/ui/components/transfer/TransferModal.jsx
Labels: ✨ feature

#103 [FEAT] Design, Card 관련 API 프론트엔드와 백엔드 연결
  src/app/child/card/complete/page.jsx
  src/app/parent/card/apply/password/page.jsx
  src/services/design.js
  src/stores/cardStore.js
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/card/ChoiceDesign.jsx
  src/ui/components/signup/Digit4PasswordButton.jsx
Labels: ✨ feature

#104 [Feat] 홈화면 api 연결
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  src/app/(auth)/signup/regform/page.jsx
  src/app/(auth)/signup/select/page.jsx
  src/app/(transaction)/transaction-history/page.jsx
  src/constants/common.js
  src/services/parents.js
  src/stores/userStore.js
  src/ui/components/atoms/Sharebutton.jsx
  src/ui/components/card-select/CardCharacter.jsx
  src/ui/components/card-select/CardIssueModal.jsx
  src/ui/components/card/InnerText.jsx
  src/ui/components/home/BlueCardBox.jsx
  src/ui/components/home/MainHome.jsx
  src/ui/components/home/child/ChildView.jsx
  src/ui/components/home/parent/HasAccount.jsx
  src/ui/components/home/parent/NoAccountView.jsx
  src/ui/components/home/parent/ParentStart.jsx
  src/ui/components/transaction/detail/ConfirmButton.jsx
  src/ui/components/transaction/transaction-history/TopBar.jsx
Labels: ✨ feature
